name: License

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [ 2020.3.30f1, 2021.2.14f1 ]

    steps:
      - uses: pCYSl5EDgo/setup-unity@master
        with:
          unity-version: ${{ matrix.unity-version }}
          has-android: True
          has-il2cpp: True
      - run: /opt/Unity/Editor/Unity -quit -batchMode -logFile -noGraphics -createManualActivationFile || exit 0
      - run: cat Unity_v${{ matrix.unity-version }}.alf